### ISSUE TITLE
Gas Limit not set by scanning QR code with gas set

### ISSUE THREAD

**Issue by Victory** [walleth/walleth#102]
Repeat:

1. Using the walleth from the play store.
2. Set the network to "ropsten"
3.  Create a qrcode for `ethereum:0x123....0?value=1000000000000000&gas=270000` replacing 0x123....0 . e.g. by using the qr code generator [here](https://jibrelnetwork.github.io/ethereum-qr-code/demo-advanced.html)
4. Scan the qrcode with wallet by clicking the camera icon in the lower right hand corner
5. Click "Show Advanced Options"

Result:  Gas Limit 21000

Expected: Gas limit 270000

**Comment by ligi** [comment]
Yes you are right - this is not supported yet - but will support it with the movement to ERC-681 which will be done soon. The library implementation is already working - tests are passing - would love some more eyes on this:
https://github.com/walleth/kethereum/commits/erc_681

Thanks for reporting anyway! Would love to understand your use-case a bit - can you elaborate on this?

**Comment by ligi** [comment]
when working on this I noticed you where writing:

> Result: Gas Limit 21000

> Expected: Gas limit 270000

I thought gas is about the gas-price. Do you want to change limit or price? Anyway it is a bit under-specified in 681 - just made a comment there to clean this up

**Comment by Victory** [comment]
The gas **limit** is going to be more important for my use case because i will be running a complicated function. If you set the gas limit too low the function will always throw an "out of gas" error, if you don't set the gas **price** high enough it just may take many blocks to get the transaction added, but eventually it should.

Both are important, but if the gas limit can't be set high enough then there is no use in signing a transaction that is doomed to fail. 

Currently, do to the very low adoption of ERC67, I am using a work around. The work around is to create a proxy contract that has as its fallback function a call to the real function on the main contract. So the qr code, at the very least needs to understand the address (of the proxy) and the gas limit.

EIP681 is an extension on ERC67 as far as i understand, hopefully it won't need the proxy work around, but until then being able to set the gas limit should be good. 

Ideally i think the community should really look towards making it easy for web3js, EIP681/ERC67 and mobile wallets to work seamlessly together to sign transactions from mobile browsers. This seems to be a very open problem at the moment.

**Comment by ligi** [comment]
Yes you are right - ideally we should discuss this further in 681 - this part is a bit under-specified currently

**Comment by Victory** [comment]
Ok, i have commented on 681

https://github.com/ethereum/EIPs/pull/681#issuecomment-345540361

**Comment by friedger** [comment]
Solved by 9552de6fc448c37a12af6eff3d7a9a952320b553 for now with gas parameter sets gas limit.

**Comment by ligi** [comment]
:+1:
