### ISSUE TITLE
Feature request allow for pasting in an EIP681/ERC67 Urls into the wallet

### ISSUE THREAD

**Issue by Victory** [walleth/walleth#104]
You should be able to copy a plaintext ERC67 address and put it in the wallet to send the transaction straight away without the need for a QR Code. 

Ideally Walleth would register with the `ethereum:` url prefix.

Maybe with something like:

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="etherum" />
                <data android:host="*" />
          </intent-filter>

**Comment by ligi** [comment]
I agree with the first-part - but the intent-filter is already set: 
https://github.com/walleth/walleth/blob/master/app/src/main/AndroidManifest.xml#L48

But sometimes intent-filters can be a problem - can you describe the scenario where it is not working?
