### ISSUE TITLE
Deleted token are not persisted

### ISSUE THREAD

**Issue by friedger** [walleth/walleth#117]
Steps to reproduce:
1. click on token symbol
1. swipe token to delete
1. select another token as default
1. click on token symbol again
1. see that the deleted token reappears

Expected result:
Deleted token does not reappear

**Comment by friedger** [comment]
@ligi Is this intended behavior? Looks like: https://github.com/walleth/walleth/blob/1ae6c15f44211feffaa6d5ead75130cbbe566957/app/src/main/java/org/walleth/activities/SelectTokenActivity.kt#L49

**Comment by ligi** [comment]
It is the current code but not really intended - it's a bug - thanks for spotting ,-)
