### ISSUE TITLE
"Only ERC67 supported currently" error when scanning address

### ISSUE THREAD

**Issue by davalb** [walleth/walleth#12]
When I use the camera-icon in the lower right corner of the main screen to scan an address I get this error: "Only ERC67 supported currently". However when I open the "Transfer"-screen and use the camera-icon there (next to the To-Address-field), I dont get this error (using the same address). I would have expected that this error appears either using both icons or not at all.

**Comment by ligi** [comment]
Thanks for the feedback! I think we should push ERC67 and try to not use context-less plain addresses - but you are right from a user perspective this is not good and I will fix it.

**Comment by ligi** [comment]
Bit more background to the error:
* the transfer activity gives the context that this 0x thing is an address
* in the mainactivity you do not really know what this is (hence ERC67 needed)

**Comment by ShadyIIV** [comment]
This error also comes up if you scan a private key. This is just a FAB with a photo Icon, so users don't know that this QR code scanner is only there to "send".

It would be nice if it would jump directly to the "import accord" screen if a private key is scanned. 

_(low priority issue)_

**Comment by ligi** [comment]
Yes this is exactly what 	c6ce7e3 is doing - now you can scan:
 * private key (e.g. from MEW)
 * JSON key (e.g. from walleth on other phone)
 * address ( then you get asked for add to addressbook or transaction

Will release a version with this change soon. Thanks for the feedback!
