### ISSUE TITLE
No data on main network

### ISSUE THREAD

**Issue by Yerontour** [walleth/walleth#124]
Look like the main network is down, in the header I have the message 'No data'. With rinkeby and ropsten I can see the block height.

I'm using Android 5.0.2

**Comment by ligi** [comment]
What version of the app are you using?

**Comment by friedger** [comment]
#62 could help

**Comment by Yerontour** [comment]
The latest, just downloaded today...can't find the version number in the app.
![screenshot_2017-11-29-16-50-33](https://user-images.githubusercontent.com/8761126/33384241-c72353e2-d525-11e7-9fc0-c649b91e6936.png)

**Comment by ligi** [comment]
can you use the share button on the top right to share the whole log? Not yet sure why there would be an ssl error for main but not for ropsten/rinkeby ..

**Comment by Yerontour** [comment]
I send to you by email.

**Comment by ligi** [comment]
pretty sure this is not relevant anymore
