### ISSUE TITLE
Ledger Nano S support

### ISSUE THREAD

**Issue by Roxxor91** [walleth/walleth#135]
I think the title is self explanatory.
I just ordered a Ledger Nano S, and it would be great if support could be added!
Thank you for developing a free alternative!

**Comment by ligi** [comment]
Yes this is planned - but not that high on my priority list because to be honest I am not a big fan of the ledger (closed source and this ugly 2 button PIN input) ..

**Comment by davalb** [comment]
I noticed there is already a ticket for this: #80

**Comment by ligi** [comment]
@davalb you are right - thanks - closing this one

**Comment by Roxxor91** [comment]
Ah. Sorry for that. Searched for "ledger", but ticket 80 has a typo "leger".

**Comment by ligi** [comment]
no worries - fixed the typo
