### ISSUE TITLE
Address clipboard attack

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#14]
Copy to clipboard was requested and implemented.
But we at least need to warn users that there is a potential attack-vector here - some malicious app could listen to the clipboard and if it detects some ethereum-address - it could replace it with its own and try to steal money this way. 
We could also listen for the clipboard our-self and detect such a malicious pattern and give the user some extra warning - that would also cover incoming addresses.
Thanks to @schildbach for the input regarding this problem

**Comment by friedger** [comment]
In #170 a warning dialog was added.
