### ISSUE TITLE
Validate that the amount field is greater than 0

### ISSUE THREAD

**Issue by davalb** [walleth/walleth#144]
I wanted to send the maximally available amount from an address and somehow (probably because of my own stupidity) sent 0 ETH. This is the tx: http://etherscan.io/tx/0x352b91f078dc3eac1787c54e6b1c10fec39bd0536405acf96c379a3c09ad0466

It would be cool, if it would be validated that the amount is greater than 0, before the transaction can be sent.

**Comment by ligi** [comment]
There might be use-cases for 0 ETH transactions - but I can add a warning
