### ISSUE TITLE
The max-amount available option uses a comma instead of a dot

### ISSUE THREAD

**Issue by davalb** [walleth/walleth#145]
I wanted to send the max amount available and used the max-option. It inserted the amount with a comma to separate the decimals, but walleth expects there to be a dot. So I got an "insufficient funds" error. Maybe this has to do with my language-settings? My phone is currently set to english.

**Comment by ligi** [comment]
Thanks for the report - do you have this problem with 0.27?

**Comment by davalb** [comment]
Yes, just checked the version and it is 0.27. Problem is still present.

**Comment by ligi** [comment]
What english locale exactly are you using - just tried 2 (English US/English NZ) and with both sweeping works for me.

**Comment by ligi** [comment]
Hm - english should always be a dot - but never mind - seems to be a problem with some devices. I end this now and do the same as @schildbach is doing in his bitcoin wallet - force everything to a dot and ignore device language settings completely - should be fixed in 0.29 then
