### ISSUE TITLE
Undesirable behavior receiving custom tokens

### ISSUE THREAD

**Issue by vkmi** [walleth/walleth#147]
Hi, I'm not sure this is an issue or simply me not understanding how the app works. I'll try to be short.
When dealing with custom tokens, the share function (green arrow, then share icon) **shares the token contract address instead of the wallet address.**

### In detail
All tested on Rinkeby test network:

- Created a token following [ethereum tutorial](https://www.ethereum.org/token)
- Decided to transfer some tokens from the main account on Ethereum Wallet (desktop) to the Walleth App.
  - I added the token (from Settings > + > ScanQrCode)
  - I selected it as token to show in the app
  - I clicked on the green arrow, shared the code to the computer (either by qr, copy to clipboard or share)
  - Transferred funds to that address
After not receiving the funds, I realized I sent the funds to an address that was the same as the address of the contract defining the custom token.

I then selected ETH as "token" to show > green arrow > share address.
Got another address, shared my custom token to that address.
I successfully received my tokens.

I don't know if it's intended but I think it's confusing that the address shared is the contract one instead of the wallet one.

**Comment by vkmi** [comment]
A similar issue happens when sending the same custom token.
It correctly reads the qrcode and correctly displays the recipient address.
After sending the wanted amount there is a discrepancy: 
In the main page it shows the correct address, when looking at the transaction detail, in the "to" field the address is again the token contract address.

**Comment by ligi** [comment]
Thanks for the report! The token-part of erc-681 is not yet implemented - will do this soon

**Comment by friedger** [comment]
Depends on https://github.com/walleth/kethereum/issues/14

**Comment by friedger** [comment]
WIP in https://github.com/friedger/walleth/tree/147/payment_uris

**Comment by friedger** [comment]
Fixed in 704fdead405c339385896d576a1833dde90bce0d

**Comment by ligi** [comment]
:+1:
