### ISSUE TITLE
send button missing and transaction list empty when importing trezor account

### ISSUE THREAD

**Issue by davalb** [walleth/walleth#148]
I imported a Trezor address into walleth that has already a balance and some incoming and some outgoing transactions. The balance was shown correctly, but the send-button was missing instead of the transactions-lists the default text "This account was just created..." was shown.

For one account the lists and button appeared after a while, but for another account the lists and button are still missing after several minutes of waiting and switching between accounts and networks.

**Comment by friedger** [comment]
Was a block number shown in the subtitle? How did you import the trezor account? 

The visibility of the send button is changing in the latest development.

**Comment by davalb** [comment]
I tried it again, just now:
Yes, there is a block number and it is equal to the current block height (5154698 as of now). This time the send-button appeared. But the lists of in- and out-going transactions did not appear.
(I am using version 0.31)

**Comment by davalb** [comment]
The way I imported it was: 
1. Opened the drawer
2. "Switch account"
3. Click on + Button
4. Entered a name and clicked on Trezor symbol
5. Connected trezor
6. Entered trezor pin

**Comment by ligi** [comment]
AFAIR the change @friedger mentioned was not yet included in 0.31 - but should be in 0.33

**Comment by davalb** [comment]
Just tried it again with version 0.34 and I don't encounter this problem anymore. Thanks. Closing this.
