### ISSUE TITLE
TREZOR support

### ISSUE THREAD

**Issue by prusnak** [walleth/walleth#15]
Couple of resources:

* https://github.com/trezor/trezor-android
* https://github.com/mycelium-com/wallet/tree/master/trezor

Feel free to reach me via email at stick@satoshilabs.com if you want to integrate TREZOR, so I can send you a free unit.

**Comment by ligi** [comment]
http://walleth.org/2017/07/14/0.17-TREZOR-AND-MORE

**Comment by prusnak** [comment]
You are the best! Will test immediately!

**Comment by ligi** [comment]
Great! Let me know if everything works fine for you.
Was a real pleasure implementing - thanks for the device and your fast reactions on questions/issues and merging PRs - this is how FOSS is really fun!
