### ISSUE TITLE
Error with geth and kethereum when compile

### ISSUE THREAD

**Issue by blind34** [walleth/walleth#188]
Hello, thank you for your project.
I have a small problem when compiling the project.

My error:

`/home/blind/Documents/PlayItOpen/Wallet/walleth-master/app/build/tmp/kapt3/stubs/noGethNoFirebaseForFDroidDebug/org/walleth/data/transactions/TransactionState.java
Warning:(7, 2) warning: There are multiple good constructors and Room will pick the no-arg constructor. You can use the @Ignore annotation to eliminate unwanted constructors.
public final class TransactionState {
             ^
Warning:warning: Supported source version 'RELEASE_7' from annotation processor 'org.jetbrains.kotlin.kapt3.ProcessorWrapper' less than -source '1.8'
/home/blind/Documents/PlayItOpen/Wallet/walleth-master/app/src/main/java/org/walleth/activities/DebugWallethActivity.kt
Error:(16, 13) Unresolved reference: ethereum
Error:(44, 18) Unresolved reference: Geth
/home/blind/Documents/PlayItOpen/Wallet/walleth-master/app/src/main/java/org/walleth/activities/OfflineTransactionActivity.kt
Error:(17, 13) Unresolved reference: ethereum
Error:(18, 13) Unresolved reference: ethereum
Error:(32, 31) Unresolved reference: geth
Error:(33, 31) Unresolved reference: geth
Error:(34, 31) Unresolved reference: geth
Error:(134, 40) Unresolved reference: Geth
Error:(142, 26) Unresolved reference: BigInt
Error:(144, 26) Unresolved reference: BigInt
Error:(168, 36) Unresolved reference: Geth
Error:(176, 22) Unresolved reference: BigInt
Error:(178, 22) Unresolved reference: BigInt
/home/blind/Documents/PlayItOpen/Wallet/walleth-master/app/src/main/java/org/walleth/data/keystore/GethBackedWallethKeyStore.kt
Error:(5, 13) Unresolved reference: ethereum
Error:(6, 13) Unresolved reference: ethereum
Error:(8, 31) Unresolved reference: geth
Error:(15, 21) Unresolved reference: KeyStore
Error:(15, 57) Unresolved reference: Geth
Error:(15, 76) Unresolved reference: Geth
Error:(30, 37) Unresolved reference: it
/home/blind/Documents/PlayItOpen/Wallet/walleth-master/app/src/main/java/org/walleth/ui/WalletPrefsFragment.kt
Error:(23, 21) Unresolved reference: geth
Error:(24, 21) Unresolved reference: geth
Error:(52, 75) Unresolved reference: GethLightEthereumService
Error:(53, 22) Unresolved reference: GethLightEthereumService
Error:(54, 51) Unresolved reference: gethStopIntent
Error:(56, 59) Unresolved reference: GethLightEthereumService
Error:(63, 33) Unresolved reference: GethLightEthereumService
Error:(63, 71) Unresolved reference: GethLightEthereumService`

I tested a lot of solution, without finding the answer.

Thx.

**Comment by ligi** [comment]
Please make sure you use the flavor withGeth - you are using the flavor noGeth which does not work yet.
