### ISSUE TITLE
How to copy address?

### ISSUE THREAD

**Issue by larroy** [walleth/walleth#189]
# Creating a issue

I'm using version 0.31  I would like to copy the address to request rinkeby funds from the faucet. I didn't find a way to do this. It would be nice to click on the account header and get the address copied.

Would a PR for this get merged?

**Comment by ligi** [comment]
Hi - please click this button:

![improved_onboarding](https://user-images.githubusercontent.com/111600/36345037-2d2c14ac-1424-11e8-87ab-6918b6547ef8.png)

and then you have the copy icon on the top right. In the next version you even have the copy icon in the main screen.

![ic_content_copy_black_24dp](https://user-images.githubusercontent.com/111600/36345069-96603d90-1424-11e8-9578-7ba3edb68709.png)
