### ISSUE TITLE
App crashes when an invalid address was entered in the addressbook

### ISSUE THREAD

**Issue by ShadyIIV** [walleth/walleth#20]
#### Issue description

The app crashes when a invalid address was entered in the address book (1 wrong character).

#### Steps to reproduce the issue

1.  Find a valid ETH address
2. Change one character and add to address book
3. Try to send Ether to that address. 

#### What's the expected result?

- Not crashing (Preferably checksum validation when creating the address book entry.)

**Comment by ligi** [comment]
Thanks for the detailed steps - love reports like this - will fix ASAP

**Comment by ShadyIIV** [comment]
Thank you. I'll report more if I find some.
