### ISSUE TITLE
Extend transaction model to function calls

### ISSUE THREAD

**Issue by friedger** [walleth/walleth#204]
Currently, transactions are stored without interpretation of the transaction.input field, this makes it difficult to find relevant transactions (e.g. for token transfers #130, #114) or in general (#1)

Proposed extension for `TransactionEntity`
```
        @Embedded
        var functionCall: FunctionCall
```
With `FunctionCall`:
```
data class FunctionCall(
        var hexSignature: String,
        var functionValue: BigInteger // whatever this is it should help to estimate the value of the relevant addresses
)
```
and a new entity
```
@Entity(tableName = "transactionToAddresses")
data class RelevantAddress(
        @PrimaryKey
        var hash: String,
        @PrimaryKey
        var address: Address
)
```
Finally the DAO should use
```
class TransactionEntityWithAddresses(
        hash: String, transaction: Transaction, signatureData: SignatureData?, transactionState: TransactionState, functionCall: FunctionCall?,
        @Relation(parentColumn = "hash", entityColumn = "hash")
        var relevantAddresses:List<RelevantAddress>
): TransactionEntity(hash, transaction, signatureData, transactionState, functionCall)
```

Technically, this implies that `TransactionEntity` must be an open (non data) class.

**Comment by ligi** [comment]
I really want those entities to be data classes and AFAIR the restriction that they cannot be data-classes in this case will be removed by room. For now I would just add another field relevantAddress (I do not see cases yet where there could be more than one - do you?) to TransactionEntity so we can query for this easily - what do you think?

**Comment by friedger** [comment]
There is the transferFrom functino in ERC20 with two additional addresses.

If you search for "address,address" in 4bytes there are a few and coming from the beercoin there is the transfer debits method.

Maybe for now we should just focus on payment and adding two extra fields relevantAddress1, relevantAddress2 should be sufficient.

**Comment by ligi** [comment]
yes you are right - kind of dislike relevantAddress1,relevantAddress2 - but seems to be the most sensible thing to do right now ;-)

**Comment by friedger** [comment]
So, I close this one and refer to #206
