### ISSUE TITLE
Funky Formatting in "Select Token"

### ISSUE THREAD

**Issue by chrishobcroft** [walleth/walleth#210]

**Comment by chrishobcroft** [comment]
When the name field exceeds a certain length, the formatting of the rows gets unusual.

See screenshots below

![screenshot_20180303-164839](https://user-images.githubusercontent.com/2212651/36936241-f9b6e2de-1f02-11e8-876b-3dfb69b87c4a.png)
![screenshot_20180303-164833](https://user-images.githubusercontent.com/2212651/36936243-f9d910d4-1f02-11e8-9ace-11c5a0398008.png)

**Comment by ligi** [comment]
Thanks for pointing this out - will try to fix soon

**Comment by chrishobcroft** [comment]
:)

**Comment by ligi** [comment]
fixed - will be rolled out with 0.34
