### ISSUE TITLE
Unresolved refrence

### ISSUE THREAD

**Issue by sunshinenote** [walleth/walleth#234]
![code](https://user-images.githubusercontent.com/16553125/37900008-94877732-311f-11e8-8ba7-fcef7743db8d.png)

**Comment by ligi** [comment]
Please switch the flavor to withGeth - you are running noGeth currently which does not yet compile

**Comment by davalb** [comment]
I have the same problem: `/Users/davalb/StudioProjects/walleth/app/src/main/java/org/walleth/activities/DebugWallethActivity.kt: (43, 17): Unresolved reference: Geth`

I seem to use the flavor noGeth: `Executing tasks: [:app:assembleNoGethNoFirebaseForFDroidDebug]`

Could you tell me how to switch to WithGeth?

**Comment by ligi** [comment]
sure - on the left you have "Build Variants" - there you can select it
![selection_022](https://user-images.githubusercontent.com/111600/38469572-2af470c6-3b57-11e8-81dc-51662fca2b9d.png)

**Comment by davalb** [comment]
Thanks for the fast reply. Now it works
