### ISSUE TITLE
Remove junit artifacts from aar

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#242]
after getting the noGeth flavor to work (which made the apk much smaller) - I looked a bit more what takes space up in the app - big chunk are the classes - but I also discovered there are some junit files in there - not big - but I still do not want this in the apk for users - not yet sure what is pulling this in - I only depend on junit in test configurations

**Comment by ligi** [comment]
the files are 

LICENSE-junit.txt 
junit/runner/logo.gif
junit/runner/smalllogo.gif

**Comment by hjubb** [comment]
adding the files to the packagingOptions closure like follows resolves this for me:
```
packagingOptions {
    ...
    exclude 'LICENSE-junit.txt'
    exclude 'junit/**'
}
```
Haven't added a PR since I wasn't sure if you'd want one off master without any of your pending changes yet, otherwise can submit one now if its still valid on its own

**Comment by ligi** [comment]
Thanks for the hint - still wonder what artifact pulled these in

**Comment by hjubb** [comment]
actually seems like it could be a deeper problem than I thought, a lot of the junit classes are still kept in the dex files in the APK as well. Not quite sure how to figure out what's referencing it (if anything) or what's adding it

**Comment by hjubb** [comment]
It looks like it may be possible to exclude junit as a dependency for the apk configuration. Doing so removes all the junit classes from the .dex files as well as the license and logo .gifs

I tested this by changing the configurations section from
```
    configurations.all { config ->
        if (config.name.contains('UnitTest') || config.name.contains('AndroidTest')) {
            config.resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.squareup.leakcanary' && details.requested.name == 'leakcanary-android') {
                    details.useTarget(group: details.requested.group, name: 'leakcanary-android-no-op', version: details.requested.version)
                }
            }
        }
    }
```

```
    configurations {

        apk.exclude group: "junit", module: "junit"

        all { config ->
            if (config.name.contains('UnitTest') || config.name.contains('AndroidTest')) {
                config.resolutionStrategy.eachDependency { details ->
                    if (details.requested.group == 'com.squareup.leakcanary' && details.requested.name == 'leakcanary-android') {
                        details.useTarget(group: details.requested.group, name: 'leakcanary-android-no-op', version: details.requested.version)
                    }
                }
            }
        }
    }
```

**Comment by hjubb** [comment]
has this change been merged @ligi ?

**Comment by ligi** [comment]
@hjubb  No - I did not merge - my CI was not happy with this change at all - and I did not really want to dig deeper as it is just a nice to have but not really critical ;-)

**Comment by ligi** [comment]
those files are not in the apk anymore
