### ISSUE TITLE
Extract OpenSourceLicenseDisplay* into library

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#245]
I had to replace com.google.android.gms:play-services-oss-licenses as it pulled in closed source play services and really fucked up dependencies. I think this could also be useful for other projects so it should be extracted into a library

**Comment by ligi** [comment]
Find the library here: https://github.com/ligi/ThirdPartyLicenseDisplay

**Comment by tasomaniac** [comment]
I always found it funny that they released that library closed source. Ironic 😀

We started to use another library but yours seems like really lightweight. Thanks for sharing.

**Comment by ligi** [comment]
You are very welcome - yea I was also really surprised that this is closed source and comes with play-services as dependency.
What library are you using now?

**Comment by tasomaniac** [comment]
I forgot and I don't have access to code ATM. 🤦‍♂️ Will report back tomorrow.
