### ISSUE TITLE
Trezor One support broken

### ISSUE THREAD

**Issue by mcgravier** [walleth/walleth#255]
Im trying to make transaction but after after confirming it on the trezor, Walleth doesn't do anything - trezor logo is displayed on cellphone but tx isn't broadcasted

Cellphone Oneplus X (android 6.0 Marshmallow)
Trezor firmware: 1.6.1
Issue happens on mainnet

**Comment by ligi** [comment]
@mcgravier thanks for reporting - looking into this currently. What firmware version version do you run on your trezor one?  context: https://github.com/trezor/trezor-android/issues/41
Also does the trezor manager from satoshi labs work for you?

**Comment by ligi** [comment]
this is a really weird error - even old versions that I am sure where working before do not work anymore. Same for TREZOR manager. This log might give a clue:

```
06-12 14:22:16.312  1572  2398 D UsbHostManager: beginUsbDeviceAdded(/dev/bus/usb/003/001) is blacklisted.
06-12 14:22:16.312  1572  2398 D UsbHostManager: beginUsbDeviceAdded(/dev/bus/usb/004/001) is blacklisted.
06-12 14:24:41.942  1572  2398 D UsbHostManager: beginUsbDeviceAdded(/dev/bus/usb/003/001) is blacklisted.
06-12 14:24:41.942  1572  2398 D UsbHostManager: beginUsbDeviceAdded(/dev/bus/usb/004/001) is blacklisted.
06-12 14:38:18.740  1572  2398 D UsbHostManager: beginUsbDeviceAdded(/dev/bus/usb/003/001) is blacklisted.
06-12 14:38:18.750  1572  2398 D UsbHostManager: beginUsbDeviceAdded(/dev/bus/usb/004/001) is blacklisted.
06-12 14:38:54.850  1572  2398 D UsbHostManager: beginUsbDeviceAdded(/dev/bus/usb/003/001) is blacklisted.
06-12 14:38:54.850  1572  2398 D UsbHostManager: beginUsbDeviceAdded(/dev/bus/usb/004/001) is blacklisted.
```
so somehow the T1 seems to be blacklisted now - getting these messages after plugging in the T1 - the Model T works without a problem. @prusnak - any hint here?

**Comment by prusnak** [comment]
No clue :-/

**Comment by mcgravier** [comment]
Trezor Manager from Satoshilabs works fine for me

**Comment by ligi** [comment]
Thanks - it was a cable issue - works using a different cable now - now I can really look into your problem

**Comment by ligi** [comment]
Fixed the bug - which was quite easy compared to this cable fuckup - this cable works fine in a normal configuration - but when used with the USB-OTG adapter it produces this "is blacklisted" problem - really weird.
Will release a version when I am home at my signing PC tonight - thanks for reporting @mcgravier

**Comment by mcgravier** [comment]
Just tested - it works fine now, thanks for fixing it

**Comment by ligi** [comment]
you are very welcome - thanks for reporting!
