### ISSUE TITLE
F-Droid version is not up to date

### ISSUE THREAD

**Issue by cfabio** [walleth/walleth#258]
I am not sure if this is the right place to post but Walleth F-Droid version is still 0.35 while on play store we are at 0.37.
Could you please look into it?

**Comment by ligi** [comment]
Thanks for the heads-up! 

The reason seems to be:

`unknown maven repo 'https://kotlin.bintray.com/kotlinx'`

I opened an issue on f-droid - unfortunately there is nothing more I can do right now: https://gitlab.com/fdroid/fdroidserver/issues/512

**Comment by ligi** [comment]
finally a solution - https://gitlab.com/fdroid/fdroiddata/merge_requests/3581 - 0.42.2 is now on f-droid
