### ISSUE TITLE
Unfortunately App has Stopped Error on Android

### ISSUE THREAD

**Issue by vmbsaturno** [walleth/walleth#285]
I compile the apk with android studio I install in android 4.4.2 and it gives me the following: 'Unfortunately App has Stopped Error on Android' error just when it finishes loading the data of the wallet.
It should be noted that when I download the application directly from the PLAYSTORE, that problem does not occur.

**Comment by ligi** [comment]
You need to select the online flavor - pretty sure this is the problem - so closing this issue. Feel free to reopen if it is not your problem
