### ISSUE TITLE
Parity Signer presents an ERC-681 QR code

### ISSUE THREAD

**Issue by Tbaut** [walleth/walleth#297]
Hey Ligi,
Just came across the warning visible in Walleth to upvote https://github.com/paritytech/parity-signer/issues/103

It's been implemented a couple months ago and we are now ERC-681 compatible (for addresses at least as we can't do it for the whole transaction, rf discussion in the above linked issue)

![image](https://user-images.githubusercontent.com/33178835/47883615-f891cf00-de2d-11e8-8c5d-8822b017a4bf.png)

**Comment by ligi** [comment]
closed via 6c10d647d3806adde83426c4500fa1c58c4d7c3c

**Comment by Fila1982** [comment]
> `[]() `

**Comment by Fila1982** [comment]
B6E4 7d8C

**Comment by Nlbgsuite** [comment]
> > `[]() `

Nlb
