### ISSUE TITLE
Support ENS names

### ISSUE THREAD

**Issue by leafcutterant** [walleth/walleth#299]
The idea is to also allow the entering an ENS name (e.g. johndoe.eth) wherever an Ethereum address can be entered, and WallETH would resolve is to an Ethereum address (but would keep displaying the ENS name). Right now these cases come to mind:

* send payment
* add account (only when it's an account solely based on an Ethereum address)
* other cases I haven't thought of

This would improve UX neatly, especially for non-techies.

If ENS names catch on in the future, the .eth part could be omitted, so that you can ask for/send a payment just by using "johndoe". I could even envision accepting ENS names without the .eth suffix from the start.

When an ENS name is used, some steps should be taken to minimize the chance of mistaken payments. I propose displaying the first two and the last distinguishing binary octets of the Etherum address (e.g. 0xdE...8a) below the entry text box in smaller font size and a lighter font color. I also propose the use of Mist-like identicons, but that will be a separate Github issue.

**Comment by ligi** [comment]
Yes - thanks for writing this. I was a bit disillusioned by ENS as someone squatted WallETH.eth - but yea still need to support ENS at some point

**Comment by leafcutterant** [comment]
I feel your pain. Squatting *is* a problem. But once a name is acquired, what can be done is marvelous: you can ask for a payment just by saying your name or a few words. No hex, no QR codes!

**Comment by ligi** [comment]
There is now finally initial ENS support in the 0.47.x version
