### ISSUE TITLE
building in android studio

### ISSUE THREAD

**Issue by s-matthew-english** [walleth/walleth#30]
when I try to build in android studio I get the following error, do you know what that's about? 

<img width="1383" alt="screen shot 2017-06-18 at 2 40 06 pm" src="https://user-images.githubusercontent.com/9053984/27260735-11916838-5434-11e7-928e-68dac28f930b.png">

Executing tasks: [:app:generateNoFirebaseForFDroidDebugSources, :app:prepareNoFirebaseForFDroidDebugUnitTestDependencies, :app:mockableAndroidJar, :app:generateNoFirebaseForFDroidDebugAndroidTestSources, :app:compileNoFirebaseForFDroidDebugSources, :app:compileNoFirebaseForFDroidDebugUnitTestSources, :app:compileNoFirebaseForFDroidDebugAndroidTestSources]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/s.matthew.english/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

:app:preBuild UP-TO-DATE
:app:preNoFirebaseForFDroidDebugBuild UP-TO-DATE
:app:checkNoFirebaseForFDroidDebugManifest
:app:preNoFirebaseForFDroidReleaseBuild UP-TO-DATE
:app:preWithFirebaseForAmazonDebugBuild UP-TO-DATE
:app:preWithFirebaseForAmazonReleaseBuild UP-TO-DATE
:app:preWithFirebaseForPlayDebugBuild UP-TO-DATE
:app:preWithFirebaseForPlayReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:app:prepareComAndroidSupportAppcompatV72531Library
:app:prepareComAndroidSupportCardviewV72531Library
:app:prepareComAndroidSupportDesign2531Library
:app:prepareComAndroidSupportPreferenceV142531Library
:app:prepareComAndroidSupportPreferenceV72531Library
:app:prepareComAndroidSupportRecyclerviewV72531Library
:app:prepareComAndroidSupportSupportCompat2531Library
:app:prepareComAndroidSupportSupportCoreUi2531Library
:app:prepareComAndroidSupportSupportCoreUtils2531Library
:app:prepareComAndroidSupportSupportFragment2531Library
:app:prepareComAndroidSupportSupportMediaCompat2531Library
:app:prepareComAndroidSupportSupportV42531Library
:app:prepareComAndroidSupportSupportVectorDrawable2531Library
:app:prepareComAndroidSupportTransition2531Library
:app:prepareComChibatchingKotprefKotpref211Library
:app:prepareComGithubLigiExtraCompats04Library
:app:prepareComGithubLigiKAXT017Library
:app:prepareComGithubLigiKAXTUI03Library
:app:prepareComGithubSalomonbrysKodeinKodeinAndroid330Library
:app:prepareComGoogleAndroidGmsPlayServicesBasement1026Library
:app:prepareComGoogleAndroidGmsPlayServicesTasks1026Library
:app:prepareComGoogleFirebaseFirebaseAnalytics1026Library
:app:prepareComGoogleFirebaseFirebaseAnalyticsImpl1026Library
:app:prepareComGoogleFirebaseFirebaseCommon1026Library
:app:prepareComGoogleFirebaseFirebaseCore1026Library
:app:prepareComGoogleFirebaseFirebaseIid1026Library
:app:prepareComJakewhartonProcessPhoenix200Library
:app:prepareComJakewhartonThreetenabpThreetenabp105Library
:app:prepareOrgEthereumGeth165Library
:app:prepareNoFirebaseForFDroidDebugDependencies
:app:compileNoFirebaseForFDroidDebugAidl
:app:compileNoFirebaseForFDroidDebugRenderscript
:app:generateNoFirebaseForFDroidDebugBuildConfig
:app:generateNoFirebaseForFDroidDebugResValues
:app:processNoFirebaseForFDroidDebugGoogleServices
Parsing json file: /Users/s.matthew.english/Projects/Ethereum/walleth/app/google-services.json
:app:processNoFirebaseForFDroidDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processNoFirebaseForFDroidDebugGoogleServices'.
> com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 25 path $

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.158 sec

**Comment by ligi** [comment]
This is happening because the google-services.json is encrypted with git-crypt. Quick fix for you is to remove:
apply plugin: 'com.google.gms.google-services'
from build.gradle

**Comment by s-matthew-english** [comment]
cool- thank you. that totally worked

**Comment by ligi** [comment]
yw - will have to tink about a better workflow for new contributors - or at least make a README entry for this fact - the error message is not really obvious ..-)

**Comment by ligi** [comment]
@daniel-sullivan thanks for the heads up. Solved this problem now - disabling firebase and offline by default so new devs do not stumble over this. Thanks again for the feedback - much appreciated!
