### ISSUE TITLE
Keystore Insufficiently Protected

### ISSUE THREAD

**Issue by mateuszk87** [walleth/walleth#319]
# Keystore Insufficiently Protected (FileBasedWallethKeyStore)

## Description 
The keystore is currently encrypted using a hardcoded key (In package org.walleth.data: DEFAULT_PASSWORD). It is not possible for users to change the encryption key or use platform security features to store the keys securely. Furthermore, the keys are also eligible for backup.

Excerpt from AndroidManifest.xml:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="org.walleth">
...
    <application
            android:allowBackup="true"
     ...
   >
...
````

## Impact
An advanced adversary with access to the device (e.g. malicious app) or access to a backup is able to retrieve the keys directly. It has to be assumed that malicious app's are able to overcome system security measures (e.g. via rooting) and can access the Walleth's local storage.

Using the extracted keys, the adversary would be able to steal user funds etc. 

## Recommendation
Different approaches could be used to make attacks more difficult:

1. Remove the ability to make backups (via Android)
2. Make keystore encryption key user definable 
3. An overall improved architecture would involve Android's TEE to encrypt sensitive data (https://source.android.com/security/keystore).

**Comment by ligi** [comment]
Thanks! Closing via 9d867bc as this is doing 1 - and there are open tickets for 2 - not yet sure about 3 - I think for this I will rather go with with the existing TREZOR support or the coming keycard support. I heard bad things from people using this API - really do not want to go this route without those keys having secured backups or them just being delegated keys that can be revoked.

**Comment by mateuszk87** [comment]
One additional note with respect to 3. I think you are referring to generate the keys in TEE, which will represent the externally owned accounts. I see all the problems with this solution, just as you described. However, you could generate keys in TEE, which would be used to encrypt the keystore on the filesystem. This would ensure that the encrypted keystore could not be attacked/cracked offline.  On the other hand, the user would still be able to export his private key (on demand). - That's just an idea :)

**Comment by ligi** [comment]
Yes - this is on the agenda - this can even be combined with fingerprint identification. Just many things to do - help very welcome !-)
But opening issues like this is also help already - does not always has to be a PR.
