### ISSUE TITLE
Trezor not working when app installed from Google Play

### ISSUE THREAD

**Issue by alenl2** [walleth/walleth#335]
When app(v0.43.2) is installed from Google Play Trezor integration dos not work. The previous version i had installed worked fine but something went wrong in the latest one. When app is compiled and installed from latest commit(7be15eca49918afab9dbf9dc277ca4b32c75d171) everything works fine. Same phone both with clean appdata.

When trying to add an account and connecting the Trezor notification to allow WallETH to access Trezor shows up, after OK is pressed nothing happens and you are left with a blank screen and the Trezor logo in the background. Logcat not showing any obvious errors or exceptions

**Comment by ligi** [comment]
Thanks for the report - will investigate.

**Comment by ligi** [comment]
I found the issue - it is the proguard configuration being to aggressive - working on it
