### ISSUE TITLE
builds not reproducible

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#356]
seeing a lot of androidX in the diffoscope report

[diffoscope link](https://gateway.ipfs.io/ipfs/QmWcHiDiKFS9X5bGhyn76rXVMfGksExRgrtgcodaSA7714)

**Comment by ligi** [comment]
filed upstream: https://issuetracker.google.com/issues/131443771

cc @akwizgran @schildbach

**Comment by schildbach** [comment]
When reporting reproducably issues, please state how you acquired the two samples.

Generally I recommend using Gradle Android plugin 2.3.3. That's the latest stable version.

**Comment by ligi** [comment]
thanks for the input - just repeated with 2.3.3  getting the same result. Just out of curiosity - where is stated that 2.3.3 is the latest stable version?

**Comment by schildbach** [comment]
It is widely known that the 3.x series is plagued with build reproducably issues. For that reason Debian is still at 2.x.

Anyway, without more information this issue report is not of much use.

**Comment by ligi** [comment]
hm - so 3.4.0 is the latest stable version not 2.3.3
anyway the problems do not seem to be releated to the build-plugin anyway as looking at diffoscope output the differences look similar between 3.4.0 and 2.3.3 - I think the jetifier/androidX is the problem
Anyway currently trying to create a minimal project to reproduce the problem

**Comment by ligi** [comment]
Heureka!

```
✓ ~/t/walleth ((7d2df013…)) sha256sum /home/ligi/kontinuum/git/walleth/./app/build/outputs/apk/noGethNoFirebaseForFDroidOnline/release/WALLETH-0.45.5-noGeth-noFirebase-forFDroid-online-release-unsigned.apk
aa5e0e7eaacc0b36b48ff8fe9aefc06db8d03529d67852f5d9443a1f693eef22  /home/ligi/kontinuum/git/walleth/./app/build/outputs/apk/noGethNoFirebaseForFDroidOnline/release/WALLETH-0.45.5-noGeth-noFirebase-forFDroid-online-release-unsigned.apk
✓ ~/t/walleth ((7d2df013…)) sha256sum ./app/build/outputs/apk/noGethNoFirebaseForFDroidOnline/release/WALLETH-0.45.5-noGeth-noFirebase-forFDroid-online-release-unsigned.apk              21:53:16
aa5e0e7eaacc0b36b48ff8fe9aefc06db8d03529d67852f5d9443a1f693eef22  ./app/build/outputs/apk/noGethNoFirebaseForFDroidOnline/release/WALLETH-0.45.5-noGeth-noFirebase-forFDroid-online-release-unsigned.apk
```

**Comment by gwap0ako025** [comment]
I just received my first transaction and i cant see any balance how to fix this thanks.
![IMG_20200411_054335](https://user-images.githubusercontent.com/62929119/79025242-c1455700-7bb7-11ea-8477-786ae0d5b3df.jpg)
