### ISSUE TITLE
Ability to use custom chains

### ISSUE THREAD

**Issue by Cyclic3** [walleth/walleth#358]
The button to add a custom chain states that it has not been implemented yet. What's the progress on this, and is there any way I can help?

**Comment by Cyclic3** [comment]
As an addition, I have a public RPC for my private chain. Would it be easier to just hook RPC to that?

**Comment by ligi** [comment]
I hope to push out a version soon with custom network support. Should be in the next version.

**Comment by Cyclic3** [comment]
Can I help in any way? This is by far the best android ethereum wallet I have used, and I would love to help out!

**Comment by ligi** [comment]
this is great to hear! Help and PRs are much appreciated. Not for this very feature as I already have a plan on how to do so and coordination would be an issue here. But other than this I really like PRs. Or also give the current version in beta a spin. Would love to roll this out to production soon so the pipeline is free for the new version. But it needs some more eye-balls as it is a very significant change

**Comment by Cyclic3** [comment]
The beta looks amazing, but the "function call" name seems to be a bit off. I shall start a new issue with this
