### ISSUE TITLE
Invalid alternative function name

### ISSUE THREAD

**Issue by Cyclic3** [walleth/walleth#359]
In the beta version (freshly built from d24c1aeebf42c80b6a272902de63b163923bac5a), the "function call" name seems to be a bit off. It prepends the correct one with an obviously invalid one, such as 'mint(uint256))' or just '', followed by "or". The smart contract source was not uploaded, so the fact that this is even detected at all is rather impressive.

Example transacation: [0x9758a0e6afc41255899585070b09f9e2c3c3a7e8968ce5ad309f4cfa4d3cb450](https://blockscout.com/eth/ropsten/tx/0x9758a0e6afc41255899585070b09f9e2c3c3a7e8968ce5ad309f4cfa4d3cb450/token_transfers)

**Comment by ligi** [comment]
thanks for the report.

the source for those is https://github.com/ethereum-lists/4bytes

but for this tx it should only be one function - mint():

https://github.com/ethereum-lists/4bytes/blob/master/signatures/a0712d68

can you make a screenshot?

**Comment by Cyclic3** [comment]
![signal-attachment-2019-04-29-202120](https://user-images.githubusercontent.com/15613874/56920935-6d338680-6abc-11e9-843e-4ee14347b86a.jpeg)

**Comment by ligi** [comment]
thanks!

**Comment by ligi** [comment]
this is really strange - just tried to reproduce and for me it looks like:

![Screenshot_1557091009](https://user-images.githubusercontent.com/111600/57200414-0adef800-6f8c-11e9-897b-c334ece80692.png)

which I would see as correct. Do you have the same behavior with a fresh install from f-droid or play?

**Comment by Cyclic3** [comment]
After uninstalling my dev build and installing a fresh version from play (f-droid is still on 0.44), this is fixed. 

Sorry about this.

**Comment by ligi** [comment]
No worries at all and thanks for opening the issue. This might still be an issue - perhaps somehow the FourByteDirectoryImpl got corrupted
Would be really helpful if this can be reproduced.
