### ISSUE TITLE
android.jar witness problem

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#363]
```
-        'bin:android-sdk:platforms:android.jar:d20853d289a5161d9cf1c1268d7923076487d4fa68c970b0733e2d5a0ccfc3c5',
+        'bin:android:platforms:android.jar:d20853d289a5161d9cf1c1268d7923076487d4fa68c970b0733e2d5a0ccfc3c5',
```

I saw this with gradle-witness. cc @akwizgran

**Comment by akwizgran** [comment]
Adding `androidApis` to `noWitness` should suppress this dependency.

**Comment by ligi** [comment]
thanks! But I would also love to have these checked. The hash is ok - just the name is a problem

**Comment by akwizgran** [comment]
Ah, got you. The name is derived from the filesystem path - a hack that works for files in the Gradle cache but can break for things like this that live elsewhere. I wonder if we can find a workaround that doesn't involve putting too much Android SDK knowledge into gradle-witness.

**Comment by ligi** [comment]
closing as we are using a different plugin now
