### ISSUE TITLE
WalletConnect.sendTransaction returns hash with double `0x` prefix

### ISSUE THREAD

**Issue by mqklin** [walleth/walleth#367]
So it returns `0x0xed1e43f7b6d29365a0d37080f03942e8274bd217349993145e6a523cbfb8c50a`
instead of `0xed1e43f7b6d29365a0d37080f03942e8274bd217349993145e6a523cbfb8c50a`

**Comment by ligi** [comment]
thanks for the report. Can you check with @pedrouid that this is not a problem in the WalletConnect js lib? There was a lot of 0x prefix things there recently
Or can you provide me with a test-dapp I can see this problem with?

**Comment by mqklin** [comment]
It's definitely not a problem with WalletConnect js, because dapp works with Tokenary and Rainbow. 
You can test it here: https://staging-terminal.zerion.io/?new
For example, try to send some asset: 
![image](https://user-images.githubusercontent.com/9456433/58233362-54ce2900-7d55-11e9-9c90-7440671e5fbd.png)

After sending don't forget to clear localStorage item to remove broken pending tx
![image](https://user-images.githubusercontent.com/9456433/58233402-6fa09d80-7d55-11e9-9d25-ca30b942f1a8.png)

**Comment by ligi** [comment]
Thanks! that it works with Tokenary and Rainbow is not a definitite indicator that it is a problem with WallETH. e.g. imagine they both don't send the 0x prefix and the wc lib adds 0x prefix - so it would look correct. But walleth sends with 0x prefix and the wc lib adds 0x prefix - that would explain the effect but WallETH would still behave correct.
PS: your dapp does not seem to react to chain-switches - is there a way to test on a testnet?

**Comment by mqklin** [comment]
No, testnet is not supported. Only mainnet.
@pedrouid could you elaborate, do you add 0x prefix or not?

**Comment by pedrouid** [comment]
The issue will definitely not be from the walletconnect-monorepo (typescript) because the responses are provided as is, you can verify this from L883

**_subscribeToCallResponse** [[L883](https://github.com/WalletConnect/walletconnect-monorepo/blob/a7e7457ec477729f7488e227001a256dfc839829/packages/core/src/index.ts#L883)]

```typescript
  private _subscribeToCallResponse (id: number): Promise<any> {
    return new Promise((resolve, reject) => {
      this.on(`response:${id}`, (error, payload) => {
        if (error) {
          reject(error)
          return
        }
        if (payload.result) {
          resolve(payload.result)
        } else if (payload.error && payload.error.message) {
          reject(new Error(payload.error.message))
        } else {
          reject(new Error('Invalid JSON RPC response format received'))
        }
      })
    })
  }

```

The issue could be however from the kotlin-walletconnect-lib adding the extra hex prefix.

**approveRequest** [[L108](https://github.com/WalletConnect/kotlin-walletconnect-lib/blob/c5ee8370375af8906a15ec4855fde3d2f5b92ad6/lib/src/main/kotlin/org/walletconnect/impls/WCSession.kt#L108)]


```kotlin
    override fun approveRequest(id: Long, response: Any) {
        send(Session.MethodCall.Response(id, response))
    }
```

**MethodCall** [[L98](https://github.com/WalletConnect/kotlin-walletconnect-lib/blob/c5ee8370375af8906a15ec4855fde3d2f5b92ad6/lib/src/main/kotlin/org/walletconnect/Session.kt#L98)]

```kotlin
    sealed class MethodCall(private val internalId: Long) {
        fun id() = internalId

        data class SessionRequest(val id: Long, val peer: PeerData) : MethodCall(id)

        data class SessionUpdate(val id: Long, val params: SessionParams) : MethodCall(id)

        data class SendTransaction(
            val id: Long,
            val from: String,
            val to: String,
            val nonce: String?,
            val gasPrice: String?,
            val gasLimit: String?,
            val value: String,
            val data: String
        ) : MethodCall(id)

        data class SignMessage(val id: Long, val address: String, val message: String) : MethodCall(id)

        data class Custom(val id: Long, val method: String, val params: List<*>?) : MethodCall(id)

        data class Response(val id: Long, val result: Any?, val error: Error? = null) : MethodCall(id)
    }
```

But looking at the code above, I can't see any string formatting happening

**Comment by ligi** [comment]
thanks for reporting and @pedrouid for the input - sorry I was sceptical first but as I saw so many prefix fixes in the WalletConnect lib it made me think this way
