### ISSUE TITLE
Add support for ERC67 for ERC20 tokens in the Request Transaction Activity

### ISSUE THREAD

**Issue by neoecos** [walleth/walleth#37]
Right now, if I change the default token the wallet shows the information about that token, but when I press the request button and puts a value to generate and ERC67 string it does not put the Token information.

An example from ERC67 

This is the same function as above, to send 5 unicorns from he sender to deadbeef, but now with a more readable function, which the client converts to byte code.

` ethereum:0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7?gas=100000&function=transfer(address 0xdeadbeef, uint 5)`

In order to fully support the ERC67 feature, the when a ERC67 URI is scanned the Walleth also needs to support that operation.

**Comment by friedger** [comment]
What is left to do here?

**Comment by ligi** [comment]
for tokens ERC-681 should be used which is supported now by great work of @friedger
