### ISSUE TITLE
Create burner doesn't have Up Nav button

### ISSUE THREAD

**Issue by TriplEight** [walleth/walleth#380]
Fresh app from Play market
Android 8.0.0
Repro:
"Create burner"
1. There's no Up Nav button
2. Back button drives you away from app

![Screenshot_20190525-143138](https://user-images.githubusercontent.com/17856421/58369389-102fc280-7efa-11e9-9c73-e052b6155fea.jpg)

**Comment by ligi** [comment]
fixed on maser
