### ISSUE TITLE
App crashes on Galaxy S9

### ISSUE THREAD

**Issue by Phistr90** [walleth/walleth#381]
Hi,

I have the Walleth version 0.45.8 installed. It crashes instantly on my S9 (Android 9, Kernel version 4.9.59-15884408) during load process. No app screen visible at any time, but a white screen for a very very brief moment.

Cheers!

**Comment by ligi** [comment]
thanks for the report!
is there any chance you could provide me with a logcat?

**Comment by Phistr90** [comment]
@ligi Can you give me an advice or point me to a tutroial or tool on how to get the logs without rooting the device?

**Comment by ligi** [comment]
where are you based? The easiest thing (with android 9) is to use adb - unfortunately for this you need to install android studio.

**Comment by Phistr90** [comment]
I have provided you with a logcat via email. meow

**Comment by ligi** [comment]
Thanks so much! This is most helpful - working on a fix.

**Comment by ligi** [comment]
Thanks for the report - that bug should be gone with 0.45.9 - without your log output it would have been much harder to find and fix.
