### ISSUE TITLE
NFC Keycard not working on Android 9

### ISSUE THREAD

**Issue by antonio-fr** [walleth/walleth#392]
On Android 9 smartphone, the NFC isn't working. When the app is on foreground, it is not recognized by the system as an NFC capable app.

I don't have many phones to test, this needs some investigations. I just feel the Android 9 is breaking NFC working with wallETH.

**Comment by ligi** [comment]
Thanks for the info! Will have a look - unfortunately it does not look I will have time for it this week - but will try out as soon as I can. Thanks so much for reporting!

**Comment by ligi** [comment]
can you try again with 0.46.3? I tested this version with 2 android 9 devices and it worked and could confirm the problem in the previous versions. If you still see this issue - feel free to reopen.

**Comment by antonio-fr** [comment]
Did you push any version after 0.45.9 on the Play Store? On my phone I can't see any further version on the Play Store.

**Comment by ligi** [comment]
sorry - it was stuck in the beta-channel - but is available in the production channel right now.

**Comment by antonio-fr** [comment]
I tested WallETH 0.46.3 with Keycard 2.2.1 on Android 9, everything works fine. 👍

**Comment by ligi** [comment]
thanks for testing and sorry for the delay!
