### ISSUE TITLE
All transaction have an error - "Could not relay transaction"

### ISSUE THREAD

**Issue by sinitcin** [walleth/walleth#401]
Hello! 
WallETH version 0.45.9.

I send a few transactions https://etherscan.io/address/0x5f36f007edbe4218c3bb7cad085db7945e84c5e4. And the last 4 transaction has been pending over 2 hour. In this time WallETH make new transaction with error - "Could not relay transaction". And after I could not send any transaction.

Moreover, the balance decreases!

**Comment by ligi** [comment]
Thanks for the report!

do you see the transactions that are marked with "Could not relay transaction" on etherscan.

**Comment by sinitcin** [comment]
@ligi If transaction has been with this error i not saw it in etherscan. But last transaction yet with this is error have send over hour after an error and i see it in etherscan.

Those. the following happens:
1. I create a payment transaction.
2. It does not send an error right away and it is not in etherscan.
3. After an indefinite time (very long), it is sent, the error disappears. I see a transaction in etherscan.

**Comment by ligi** [comment]
hm - wonder if it has something to do with this: https://www.reddit.com/r/ethereum/comments/d970xz/infuraio_breaks_backward_compatibility_for_web3js/
really need to get away from infura towards INCUBED

**Comment by sinitcin** [comment]
You can check if create 10-20 a transaction with small price and normal gas price

**Comment by ligi** [comment]
so it happens after 10-20 transactions - quite an expensive test - will try it on rinkeby/ropsten first ;-)
And just out of curiosity: what is your use case?

**Comment by sinitcin** [comment]
Our organization make a mPOS for pay in shops with a cryptocurrency. WallETH has supported right format of QR, we take it for test.

**Comment by sinitcin** [comment]
And we in Berlin too =)

**Comment by ligi** [comment]
Awesome - then we should for sure meet up at some point. Will try to fix your problem - but need to find a way to reproduce it without spending too much gas. I think it should be possible to reproduce on ropsten. Maybe the change to INCUBED will already help - I guess INFURA is the problem here.
Thanks so much for the testing - much appreciated!

**Comment by sinitcin** [comment]
Thank you very much! I agree with you =)
