### ISSUE TITLE
Make it easier to export keys

### ISSUE THREAD

**Issue by sinitcin** [walleth/walleth#402]
Hello! 

How can i export my keys from WallETH to MyCrypto App?

**Comment by ligi** [comment]
yes you can - in the account list on the top right there is the icon so you can export - really need to make this more clear and easier to find

**Comment by sinitcin** [comment]
But MyCrypto App don't understand a format key, it show me the error:
>> This is not a valid wallet file.

**Comment by ligi** [comment]
I just tried it with MyCrypto v1.7.1 and it works as intended (both copying the key and saving as a file)
was there perhaps a problem in transfering the file from phone to PC?

**Comment by sinitcin** [comment]
I too have version v1.7.1 and i no have problem for transferring key file. Do you select in MyCrypto the button "Keystore File"?

**Comment by ligi** [comment]
yes - I selected "Keystore File" - unfortunately I am not even able to get the error you get with an invalid JSON file - perhaps the myCrypoto team can shed some light on this. Opened an issue there: https://github.com/MyCryptoHQ/MyCrypto/issues/2757
What could also really help if you create a new account and export the key and send it to me. I do not want a key with value attached - an empty account would be better for me.

**Comment by ligi** [comment]
This issue is just closer as I made it now easier to export keys - let's continue with getting to the ground of why you cannot import to MyCrypto in #403 - but I need a way to reproduce this (e.g. with the suggestion above) - otherwise my hands are tied

**Comment by sinitcin** [comment]
Ok, let's begin =) 
1. Open WallETH
2. Select in left panel `Accounts`
3. Select button `Pin` in my account
4. Enter my pin
5. Enter export password
6. Touch on menu item `Save`
7. Select `Download` folder for save *.key file 
8. Connect phone to the PC as for transferring files 
9. Move *.key file to the PC
10. My host is Ubuntu 19.04 x86_64 and for start `MyCrypto` i execute the file `linux-x86-64_1.7.1_MyCrypto.AppImage`
11. After run MyCrypto i click on the button `Keystore File`
12. Click on `Select wallet file`
13. We have an error from subj =(

Maybe in Ubuntu the `MyCrypto` application does not read the encoding correctly?!

**Comment by ligi** [comment]
I am also using linux-x86-64_1.7.1_MyCrypto.AppImage on ubuntu (18.04.3 though). Would you be able to send me such a key file of a fresh and empty account so I can try this one on my side?

**Comment by sinitcin** [comment]
I understood how the error occurred =) I create new account and export with password consisting only a numbers and MyCrypto load *.key file without errors, but if i use this password `4jD253MxhE` a error has occurring

**Comment by ligi** [comment]
very interesting - thanks so much for the info - will look into this.

**Comment by ligi** [comment]
for me it also works with this exact password and a PIN for me ;-(
can you send me a key-file that is not working for you?
