### ISSUE TITLE
Tx isnt broadcasted

### ISSUE THREAD

**Issue by Phistr90** [walleth/walleth#405]
Hey,

so I had the really annoying problem once again that my tx wasnt broadcasted and I had  to manually scan the signed RLP and submit the signed tx via the broadcasting tool from etherscan.

Is there a way to retry to broadcast the tx?
Why can't I copy the raw tx? Why is it only shown as qr? 
(I needed to get a second device in order t scan it...)

Cheers! 

Philipp

**Comment by ligi** [comment]
Thanks for the report!
Retrying should be done automatically - will look into the code again what could be edge-cases when this is not done. Would love to avoid a "retry" button.
Will do a copy button though. This is a good idea.
