### ISSUE TITLE
There is a problem with estimating gas limit.

### ISSUE THREAD

**Issue by chrishobcroft** [walleth/walleth#425]

**Comment by ligi** [comment]
Thanks for reporting - maybe relevant here: https://github.com/MetaMask/metamask-extension/issues/7709

**Comment by ligi** [comment]
more context: https://ethereum-magicians.org/t/improving-gasestimation/3907

so there is room for improvement at the node layer here - will close this with a workaround (multiplying value from node with magic number)  and open a new ticket regarding upsteam improvements afterwards.
