### ISSUE TITLE
NullPointerException in TrezorSignTransactionActivity.kt when getting message for state READ_ADDRESS

### ISSUE THREAD

**Issue by hjubb** [walleth/walleth#433]
Getting a crash consistently on the [TrezorSignTransactionActivity.kt](https://github.com/walleth/walleth/blob/fe970095baf5e4f1b110957d8e58817fbe464a6c/app/src/main/java/org/walleth/trezor/TrezorSignTransactionActivity.kt) when trying to get the `currentBIP44` value as it handles the `READ_ADDRESS` state in `getMessageForState()`. Current store version / master affected.

It looks like a change made in commit e990f2b1ba7c668130b01a28038bcf661709ecbd to use a coroutine instead of the async callback removed the setting of `currentBip44` in the `TrezorSignTransactionActivity.onResume()` function

I made a change locally that seemed to fix it and allowed me to send Trezor transactions, including from both the default and non-default BIP44 paths. I can create a PR for that attached to this issue, if it's missing anything or you have any other thoughts about what that change might affect let me know!

**Comment by ligi** [comment]
Thanks for the insight - you are completely correct
