### ISSUE TITLE
Use checksummed format for Ethereum addresses

### ISSUE THREAD

**Issue by prusnak** [walleth/walleth#47]
I don't think it is THAT important, but most of the Ethereum wallets I've seen use 

0x1f815D67006163E502b8eD4947C91ad0A62De24e

rather than plain lowercase addresses

0x1f815d67006163e502b8ed4947c91ad0a62de24e

and I expect users are used to seeing this more in the wild.

**Comment by zaeleus** [comment]
For reference: [Mixed-case checksum address encoding (EIP-55)](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md)

**Comment by ligi** [comment]
@zaeleus thanks - much nicer link than the issue to this EIP I had open before ;-)
