### ISSUE TITLE
Could not sign transaction:scaler Is not in the interval [1,n-1]

### ISSUE THREAD

**Issue by hayjaydabtclegend** [walleth/walleth#472]
Please when I want to send it keeps saying could not sign transaction scaler is not in the interval [1,n-1]

**Comment by ligi** [comment]
After email communication with you: as it is an imported key and it is also not importable in myCrypto: not sure if there is anything I can do. Also I am still curious where the export was from.

**Comment by ligi** [comment]
closing this - looks like this was just a badly exported key - nothing I can do with WallETH in this case. As I see nothing actionable here I will close - but feel free to reopen if you see something I can do here.
