### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [walleth/walleth#485]
# Creating a issue

Thanks for your feedback - this is really important to improve the project!
Please make issues atomar and closeable. This means if you have one idea for an enhancement and experience a bug - please submit 2 issues and don't pack it all in one.
Please try to give a lot of detail - so ideally the issue can be reproduced. At the very minimum it is important to know what version of the app and what version of android you are using and where you got the app from.

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, The button in the red box is half covered. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.
App version is 0.48.2, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="444" alt="bug-walleth_482" src="https://user-images.githubusercontent.com/18572115/103153483-cee55000-47cb-11eb-8e78-eca514964bf0.png">

**Comment by ligi** [comment]
Thanks for reporting! Fixed in the next version
