### ISSUE TITLE
TREZOR One firmware support for 1.10.1

### ISSUE THREAD

**Issue by GuizzyQC** [walleth/walleth#530]
I'm not sure if this is simply a matter of adjusting the firmware version check or if there are actual changes that make WallETH incompatible with the latest firmware revisions, but it is currently impossible to add a TREZOR address from a TREZOR One with the latest firmware. The error message is "For Trezor model ONE only Firmware 1.8.X or 1.9.X is supported but found 1.10.1".

**Comment by ligi** [comment]
Oh thanks for letting me know - need to check out the new firmware and yea - most likely I just need to adjust the check

**Comment by exzombie** [comment]
I see you updated the version check, but not the error message. Happens to me all the time :smile: . Would it be a bad idea to allow future versions as well? Does Trezor have compatibility guarantees for the USB interface?

**Comment by ligi** [comment]
Yea - was also thinking about that. Got a lot of bad reviews on Google Play because of outdated versions. But I am not sure about just allowing future versions - it could just break in a worse/undefined way there and AFAIK TREZOR has no guarantees here. A protocol version would really be nice.

cc @prusnak

**Comment by prusnak** [comment]
We never break the protocol intentionally.

**Comment by ligi** [comment]
Interesting - not even with a major version? So I can just assume that when it works with one version it will also work with all following versions? Bit scared - but maybe I just remove the check then - or just check for the major version and accept all minor/patch versions then.

**Comment by prusnak** [comment]
Yes, just keep the minimum version check (i.e. 1.8.0 and older).

**Comment by ligi** [comment]
Thanks for the insight - will keep the minimum then and also the major check I guess. And If you ever break compatibility for the minor version: I know where you work ;-)

**Comment by prusnak** [comment]
Haha :D
