### ISSUE TITLE
Optimism transactions not published

### ISSUE THREAD

**Issue by CodeSandwich** [walleth/walleth#531]
I'm testing our DApp on Optimism Kovan. It sends transactions over WalletConnect to a mobile wallet to sign and it pushes it to the network. WallEth works fine with this flow for some transactions. But others after signing and publishing never become visible in the block explorer.

I've tried setting gas price to 0.015 as Optimism requires (WallEth suggests 0) and modifying the nonce (WallEth suggests too high).

**Comment by ligi** [comment]
Thanks for the report - is the DApp public so I can try myself? Bit surpised by the wrong nonce though - do you have pending transactions?

**Comment by CodeSandwich** [comment]
Sure, it's Radicle Upstream: https://github.com/radicle-dev/radicle-upstream, I highly recommend checking it out :)

Thank you for picking it up immediately and I'm sorry about the noise. It was my fault: the contract was misconfigured and the call was probably silently exceeded the transaction gas limit.

About the nonces: WallEth seems to be looking at the transactions included in the blockchain and all transactions it has singned, no matter if they are included or not. Signing and sending a failing transaction with nonce 4 will make the next default nonce 5.
