### ISSUE TITLE
Need Receive button

### ISSUE THREAD

**Issue by riartem** [walleth/walleth#54]
How to share address of first wallet for receiving some amount? 
There is no button to it. Only ability to view full address on "Switch account" page.

**Comment by ligi** [comment]
It is the green button next to the account - but thanks for the feedback anyway - seems I really need to prioritize #49

**Comment by riartem** [comment]
Oh, I found it finally. I think adding button to main menu or top bar or even simple grey button on center screen (e.g. something closer to style guides) will be more useful.
Otherwise, thank you for quick feedback and help. 
I tryed that application and it already works (with custom tokens too). I think it will have the good future.

(sorry for possible errors in my messages, I am not native english speaker)
