### ISSUE TITLE
Is my Wallet gone? Cant't find FAQ

### ISSUE THREAD

**Issue by laleluke** [walleth/walleth#549]
Hello,
first of all I'm sorry to post here but i didn't find any other place for asking questions.

I'm using Walleth on my FP3 and installed it from F-Droid. Was always up to date.
I used a Pin-Protected key.
I should have received a payment 2 days ago. In etherchain it said the transaction is done but i did not get the Eth.
So i tried reinstalling the app without checking if i backed up my key, which i thought i did prior but did not.

Is there any way to recover my key? I do have the pin and my adress and I'm quite sure I managed to log in with those 2 credentials before...

**Comment by Daoudia** [comment]
Nein du musst einen neuen regenerieren 

Gesendet von Yahoo Mail auf Android 
 
  Am So., Okt. 3, 2021 at 14:24 schrieb ***@***.***>:   


Hello,
first of all I'm sorry to post here but i didn't find any other place for asking questions.

I'm using Walleth on my FP3 and installed it from F-Droid. Was always up to date.
I used a Pin-Protected key.
I should have received a payment 2 days ago. In etherchain it said the transaction is done but i did not get the Eth.
So i tried reinstalling the app without checking if i backed up my key, which i thought i did prior but did not.

Is there any way to recover my key? I do have the pin and my adress and I'm quite sure I managed to log in with those 2 credentials before...

**Comment by ligi** [comment]
Sorry but without the key there is nothing you can do. We are non-custodial and do not hold copies of your key and the key is the only way to access your funds. Hope it was not much.
That the balance was not reflected for a bit is caused by INCUBED being down currently - hope it comes back on soon.
