### ISSUE TITLE
Transactions remain pending/ I'm new to crypto

### ISSUE THREAD

**Issue by ucefelmejjati** [walleth/walleth#556]
# Creating a issue

Thanks for your feedback - this is really important to improve the project!
Please make issues atomic and closable. This means if you have one idea for an enhancement and experience a bug - please submit 2 issues and don't pack it all in one.
Please try to give a lot of detail - so ideally the issue can be reproduced. At the very minimum it is important to know what version of the app and what version of android you are using and where you got the app from.

**Comment by ucefelmejjati** [comment]
Hello, 
I'm new to crypto and I just wanted to send ETH from a coinbase wallet to my coinbase trading wallet. 
I found that gas fees are so high for me as a beginner, so I modified the gas fees to 1 gwei and I sent all the ETH that I own which is 0.1. 

I found the hash on etherscan but it says it's still pending. I'm aware now of what I did and I regret it. 
It says : this txn hash was found in our secondary node and should be picked up by our indexer in a short while. 

The hash is : 0xda5c5d40090b307816815406f4e745afc0433af198961c2a2e03e798468469f4

Block is pending, timestamp is pending also. 

I searched on web, I found that the gas fee was so low that it could be lost. 

Can you PLEASE help!!!

**Comment by ligi** [comment]
You need to increase the gas-fee - we are in the process to make this better. Currently the app is not that beginner friendly - maybe for now export your key and import it in another one
