### ISSUE TITLE
Offline transaction test failed

### ISSUE THREAD

**Issue by soldier9945** [walleth/walleth#56]
Hi!

I have tried to test the offline transaction function you implemented in Walleth, but I couldn't get the QR code with the transaction data.

What I have done:
- Created an "Online Wallet" on my main smartphone
- Got 3 ETH from the Faucet to that "Online Wallet"
- Copied the APK to an offline, freshly reset android phone, no Wifi connected, no SIM
- Opened Walleth, renamed the automatically created account to "Offline Wallet"
- On my main phone, I added a new account by scanning the public address from the "Offline Wallet"
- Sent 1 ETH from the "Online Wallet" to the "Offline Wallet"
- From the main smartphone I selected my "Offline Wallet" without private key (watch-only?)
- I set up a transfer of all the funds on that "Offline Wallet" to the "Online Wallet"
- Tried to validate the transaction thinking there would be a QR Code shown, but there wasn't

After some trial and nothing, I'm lost and I don't know where the QR Code of the transaction is supposed to show up?

Can you help me? Thanks!

**Comment by ligi** [comment]
Thanks for the detailed report - I could reproduce it and I will write a fix and a test for this.

**Comment by soldier9945** [comment]
Any news on this issue? I'd be glad to help testing a fixed version.

**Comment by soldier9945** [comment]
Hi, I've just retested the offline signing of a transaction using the main net (a very small amount) on Walleth 0.21 with both devices.

It seems to work now on the online device, I can create and see the unsigned transaction and QR code when I select the entry.

Now on the offline device I can't seem to find an option to read the unsigned transaction QR code, sign it and show the signed transaction as a new QR code.

Did I misunderstand the way offline signing is intended in this app or is there still some code missing to do what I tried?

What I have done:

From the online phone: 
1. Added my wallet address on my main smartphone (online) without private key
2. I set up a transaction for a small amount of ETH to another of my wallet addresses.
3. Now I can see the unsigned transaction on the right column (send TXs) and I can select it showing the transaction details and the QR code of the unsigned transaction (great! 😄)

From the offline phone: 
1. Copied the APK to an offline, freshly reset android phone, no Wifi connected, no SIM
2. Imported my unencrypted private key from my printed paper wallet (the key corresponding to the address configured as watch only on the online device)
3. Tried to sign the unsigned transaction by:
- No green arrow showing to create a transaction (phone is offline so balance is 0, that's why)
- Using the bottom right camera icon to scan the transaction QR code
-- choosing "Perform transaction" after scanning
-- app interprets it as a destination address but scanned address is wrong because it's not the same as the TX address shown on the online phone
-- app shows the form to create a new transaction
- Using the Offline Transaction option from the menu (top left), doesn't seem to be the way to go because it says "Relay Transaction" which seems to imply this is to be used on the online phone to broadcast an already signed transaction
-- Tried nonetheless, app seems to read the QR code but the TX address is not the same as the one shown on the online phone

Thanks for your help / clarification on the matter

PS: I see you were working on this issue a few hours ago, maybe I'm posting too soon. Eager to test this! 😋 because the "competition" doesn't seem to offline sign using a smartphone, WHY??? 😨  https://airgap.it/ for example)

**Comment by ligi** [comment]
Thanks again for your input and sorry for the delay with the fix - had some other stuff todo in preparation for DevCon3. I found the issue - slipped in with network-switching and geth update - and will try to fix it ASAP and would be really happy if you could retest.
What the referenced commit is doing: fixes a flow when you want to relay a signed tx coming from MEW - also in the area of offline transactions - but does not yet fix your flow (yet)

**Comment by soldier9945** [comment]
No problem, I'm glad for your project because I would have to learn programming for Android prior to getting to what I want 😉. And as stated previously, I'm here to help.
