### ISSUE TITLE
Cannot import go-ethereum wallet

### ISSUE THREAD

**Issue by mcizek-2** [walleth/walleth#569]
I have created a go-ethereum wallet in Linux using the Etherwall gui. I wanted to export it to the walleth app on my phone. I used the Import key. I tried the JSON format as that seems to make most sense. I imported it using a QR code, but then when I put the passphrase I got the following error:

"Cannot decrypt this key with the RAM available on this device"

Which seems strange, because after closing all apps I should have about 1.2Gb of RAM available, which I would presume should be more than enough to decrypt an ethereum private key?

**Comment by ligi** [comment]
on mobile we use `--lighkdf` for exactly this reason - normal scrypt paramenters require a lot of RAM and is not really suitable for mobile. But tbh I did not found numbers with a fast search.

**Comment by mcizek-2** [comment]
> on mobile we use `--lighkdf` for exactly this reason - normal scrypt paramenters require a lot of RAM and is not really suitable for mobile. But tbh I did not found numbers with a fast search.

It did work with the parameter --lightkdf. Thanks.

**Comment by l29ah** [comment]
What can be done about an existing non-lightkdf go-ethereum wallet to import it into walleth?

**Comment by l29ah** [comment]
Okay, used `ethkey inspect --private` and pasted the private key in walleth, and it worked.
