### ISSUE TITLE
Update to geth 1.7.2

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#70]

**Comment by friedger** [comment]
Should be 1.7.3 by now.
What are the issue here?

**Comment by friedger** [comment]
Done in https://github.com/walleth/walleth/commit/57bc23bd0e4d49e6d4f861e8c15c47ed27219f3b

**Comment by ligi** [comment]
This was the issue: https://github.com/ethereum/go-ethereum/issues/15331
AFAIK 1.7.2 never got released for android because of this issue - but now 1.7.3 is available recently - and experiments with this look good - will release a version based on it soon.

**Comment by ligi** [comment]
0.25 contains 1.7.3
