### ISSUE TITLE
Settings for gas price

### ISSUE THREAD

**Issue by Phistr90** [walleth/walleth#97]
Proposal: Make an option for setting the the default gas price in the setting menu or remember the gas price setting from the last transaction.

**Comment by ligi** [comment]
Good suggestion - I tend to go the route of saving it as a default value (per chain) - perhaps after asking the user (so he also knows about it) 
Flow would be the following:
 - user makes a transaction with a gas-price that is different than the one saved for the current chain
 - When sending the transaction the app asks "Set gas price as default"?

Not yet sure if I should use a SnackBar or AlertDialog
I think this way the feature is more discoverable than in the settings - also it helps fight a huge settings area which is rarely good UX

**Comment by friedger** [comment]
Fixed by https://github.com/walleth/walleth/pull/163

**Comment by ligi** [comment]
You can directly close issues like this if you wish @friedger - if you do not have permissions to do so - ping me and I will try to fix this ;-)

**Comment by friedger** [comment]
@ligi I don't have permission to close it, nor to assign the task to me.

**Comment by ligi** [comment]
Hopefully you should have the permission now
